config/routes.rb
Rails.application.routes.draw do
  resources :profiles, only: [:index, :show]

  resources :line_items do
  	put :replace_weekly_line_item
  	
  end
  resources :recipe_collection
  devise_for :users
  resources :recipes do
    put :favorite, on: :member
  end

  root "recipes#index"

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  	@user = User.all
    #@users = User.page(params[:page])
    @line_items = LineItem.where(:user_id == current_user.id)
  end

  def show
  	@user = current_user

    @line_items = LineItem.where(:user_id == current_user.id)
    # @user = User.where(username: params[:id])
      #@line_items = @user.line_items.recipes(params[:line_items])
    #else
     # flash[:alert] = 'Profile not found.'
      #redirect_to profiles_path
    #end
    
    
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/index.html.erb
<h1>Profiles#index</h1>
<p>Find me in app/views/profiles/index.html.erb</p>
<p><%= @line_items %></p>

app/views/profiles/show.html.erb
<h2> My Favorite Recipes <%# link_to @user.email, profile_path(@user) %></h2>
<%= @user.username %> <br>
<%= @user.email %>




<br><br>
<%= @user.recipes.count %>
<br><br>
<% @line_items.each do |line_item| %>
<%= line_item.recipe.title %> <br>
<%= line_item.last_eaten %> <br>
<%end%>
<table style="width: 100%">
  <thead>
    <tr>
      <th>Url</th>
      <th>User</th>
    </tr>
  </thead>

  <tbody>
  <% @line_items.each do |item| %>
    <tr>
    <td><%=  item[0] %></td>
    <td><%# @user.username %></td>
  </tr>
<% end %>
  </tbody>
</table>



<%= link_to 'Back', profiles_path %>