config/routes.rb
Rails.application.routes.draw do
  resources :profiles, only: [:index, :show]

  resources :line_items do
  	put :replace_weekly_line_item
  	
  end
  resources :recipe_collection
  devise_for :users
  resources :recipes do
    put :favorite, on: :member
  end

  root "recipes#index"

end

app/models/recipe_collection.rb
class RecipeCollection < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	

	
end

app/controllers/recipe_collection_controller.rb
class RecipeCollectionController < ApplicationController
  before_action :set_recipe_collection, only: [:show, :edit, :update, :destroy]

  # GET /recipe_collections
  # GET /recipe_collections.json
  def index
    @recipe_collection = RecipeCollection.all
  end

  # GET /recipe_collections/1
  # GET /recipe_collections/1.json
  def show
  end

  # GET /recipe_collections/new
  def new
    @recipe_collection = RecipeCollection.new
  end

  # GET /recipe_collections/1/edit
  def edit
  end

  # POST /recipe_collections
  # POST /recipe_collections.json
  def create
    @recipe_collection = RecipeCollection.new(recipe_collection_params)

    respond_to do |format|
      if @recipe_collection.save
        format.html { redirect_to @recipe_collection, notice: 'Recipe collection was successfully created.' }
        format.json { render :show, status: :created, location: @recipe_collection }
      else
        format.html { render :new }
        format.json { render json: @recipe_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_collections/1
  # PATCH/PUT /recipe_collections/1.json
  def update
    respond_to do |format|
      if @recipe_collection.update(recipe_collection_params)
        format.html { redirect_to @recipe_collection, notice: 'Recipe collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_collection }
      else
        format.html { render :edit }
        format.json { render json: @recipe_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_collections/1
  # DELETE /recipe_collections/1.json
  def destroy
    @recipe_collection.destroy
    respond_to do |format|
      format.html { redirect_to recipe_collections_url, notice: 'Recipe collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe_collection
      @recipe_collection = RecipeCollection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_collection_params
      params[:recipe_collection].permit( :update, :line_item_id)
    end
end

app/helpers/recipe_collections_helper.rb
module RecipeCollectionsHelper
end

app/views/recipe_collection/_form.html.erb
<%= form_for(@recipe_collection) do |f| %>
  <% if @recipe_collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe_collection.errors.count, "error") %> prohibited this recipe_collection from being saved:</h2>

      <ul>
      <% @recipe_collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipe_collection/edit.html.erb
<h1>Editing Recipe Collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe_collections %> |
<%= link_to 'Back', recipe_collections_path %>

app/views/recipe_collection/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recipe Collections</h1>
<p> Hi, <%= current_user.email %> !</p>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipe_collection.each do |recipe_collection| %>
      <tr>
        <td><%= recipe_collection.id %></td>
        <td><%= link_to 'Show', recipe_collection %></td>
        <td><%= link_to 'Edit', edit_recipe_collection_path(recipe_collection) %></td>
        <td><%= link_to 'Destroy', recipe_collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe collection', new_recipe_collection_path %>

app/views/recipe_collection/new.html.erb
<h1>New Recipe Collection</h1>

<%= render 'form' %>

<%= link_to 'Back', recipe_collections_path %>

app/views/recipe_collection/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<p>Hi, <%= current_user.email %>!</p>
<h2>Your Recipe Collection</h2>
<ul>
	<% @recipe_collection.line_items.each do |item| %>
	<li><%= item.recipe.title %></li>
	<% end %>
</ul>

<%= link_to 'Edit', edit_recipe_collection_path(@recipe_collection) %> |
<%= link_to 'Back', recipe_collection_path %>