config/routes.rb
Rails.application.routes.draw do
  resources :profiles, only: [:index, :show]

  resources :line_items do
  	put :replace_weekly_line_item
  	
  end
  resources :recipe_collection
  devise_for :users
  resources :recipes do
    put :favorite, on: :member
  end

  root "recipes#index"

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_many :line_items 
	before_destroy :ensure_not_referenced_by_any_line_item
  has_many :ingredients
  has_many :directions
 	has_many :users, :through => :line_items
 	#belongs_to :user
 	has_many :favorited_by, through: :line_items, source: :user

accepts_nested_attributes_for :ingredients, 
															reject_if: :all_blank, 
															allow_destroy: true
accepts_nested_attributes_for :directions, 
															reject_if: :all_blank, 
															allow_destroy: true
validates :title, :description, :image, presence:true
	has_attached_file :image, styles: { medium: "400x400#" }
	  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	private
		#ensure that there are no line items referencing this recipe
		def ensure_not_referenced_by_any_line_item
			if line_items.empty?
				return true
			else
				errors.add(:base, 'Line items present')
				return false
			end
		end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	before_action :find_recipe, only: [:show, :edit, :update, :destroy, :favorite]
	before_action :authenticate_user!, except: [:index, :show]
	#before_destroy :ensure_not_referenced_by_any_line_item


	def index
		@recipe = Recipe.all
	end

	def show
		
	end

	def new
		@recipe = current_user.recipes.build
	end

	def create
		@recipe = current_user.recipes.build(recipe_params)
		
		if @recipe.save
			redirect_to @recipe, notice: "Successfully created new recipe!"
		else
				render 'new'
		end
	end

		def edit
		end

		def update
			if @recipe.update(recipe_params)
				redirect_to @recipe
			else
				render 'edit'
			end
		end

		def favorite
    type = params[:type]
    if type == "favorite"
      current_user.favorites << @recipe
      redirect_to :back, notice: 'You favorited #{@recipe.name}'

    elsif type == "unfavorite"
      current_user.favorites.delete(@recipe)
      redirect_to :back, notice: 'Unfavorited #{@recipe.name}'

    else
      # Type missing, nothing happens
      redirect_to :back, notice: 'Nothing happened.'
    end
  end


		def destroy
			@recipe.destroy
			redirect_to root_path, notice: "Successfully deleted recipe."
		end

	private
	def recipe_params
		params.require(:recipe).permit( :title, :description, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
	end

	def find_recipe
		@recipe = Recipe.find(params[:id])
	end

	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'Line Items present')
			return false
		end
	end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_direction_fields.html.haml
.form-incline.clearfix
	.nested-fields
		= f.input :step, input_html: {class: "form-input form-control"}
		= link_to_remove_association "Remove", f, class: "form-button btn-default"

app/views/recipes/_form.html.haml
= simple_form_for @recipe, html: { multipart: true } do |f|
	- if @recipe.errors.any?
		#errors
			#p
				= @recipe.errors.count
				Prevented this recipe from saving
			%ul
				- @recipe.errors.full_messages.each do |msg|
					%li= msg
	.panel-body
		= f.input :title, input_html: { class: 'form-control' }
		= f.input :description, input_hmtl: { class: 'form-control' }
		= f.input :image, input_hmtl: { class: 'form-control' }

		.row
			.col-md-6
				%h3 Ingredients
				#ingredients
					=f.simple_fields_for :ingredients do |ingredient|
						= render 'ingredients_fields', f: ingredient
					.links
						= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button"


			.col-md-6
				%h3 Directions
				#directions
					=f.simple_fields_for :directions do |direction|
						= render 'directions_fields', f: direction
					.links
						= link_to_add_association 'Add Directions', f, :directions, class: "btn btn-default add-button"
						
	= f.button :submit, class: "btn btn-primary"

app/views/recipes/_ingredient_fields.html.haml
.form-incline.clearfix
	.nested-fields
		= f.input :name, input_html: {class: "form-input form-control"}
		= link_to_remove_association "Remove", f, class: "form-button btn-default"

app/views/recipes/edit.html.haml
%h1 Edit Recipe
= render 'form'

app/views/recipes/index.html.haml
-@recipe.each_slice(3) do |recipes|
 .row
  - recipes.each do |recipe|
   .col-md-4
    .recipe
     .image_wrapper
      =link_to recipe do
       = image_tag recipe.image.url(:medium)
      %h2= link_to recipe.title, recipe

app/views/recipes/new.html.haml
%h1 New Recipe

= render 'form'
%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/recipes/show.html.erb
.main_content

  #recipe_top.row
    .col-md-4
     <% image_tag @recipe.image.url(:medium), class: "recipe_image" %>
    .col-md-8
      #recipe_info
        <h1> <%= @recipe.title %> </h1>
        <% if current_user %>
        <%= link_to "favorite",   favorite_recipe_path(@recipe, type: "favorite"), method: :put %>
        <%= link_to "unfavorite", favorite_recipe_path(@recipe, type: "unfavorite"), method: :put %>
        <% end %>

        <%= button_to 'Add to My Recipes', line_items_path(recipe_id: @recipe) %>
        
        <p class="description"> <%= @recipe.description %> 
        </p>
        <p>
          Submitted by:
         <%# @recipe.user.email %>
        </p>

  .row
    .col-md-6
      #ingredients
        <h2> Ingredients </h2>
        <ul>
          <% @recipe.ingredients.each do |ingredient| %>
            <li><%= ingredient.name %><li>
        </ul>
       <% end %>

    .col-md-6
      #directions
        <h2> Directions </h2>
        <ul>
          <% @recipe.directions.each do |direction| %>
            <li><%= direction.step %><li>
        </ul>
       <% end %>

  .row
    .col-md-12
      <%= link_to "Back", root_path, class: "btn btn-default" %>
    <% if user_signed_in? %>
      <%= link_to "Edit", edit_recipe_path, class: "btn btn-default" %>
      <%= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default" %>
    <% end %>