config/routes.rb
Rails.application.routes.draw do
  resources :profiles, only: [:index, :show]

  resources :line_items do
  	put :replace_weekly_line_item
  	
  end
  resources :recipe_collection
  devise_for :users
  resources :recipes do
    put :favorite, on: :member
  end

  root "recipes#index"

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  
  belongs_to :user #remove?
  belongs_to :recipe
  
  scope :created_by, -> (user_id) { where(user_id: user_id) }
 
  scope :last_week, lambda {where("line_items.last_eaten >= ?", 8.days.ago.to_date)}
  
 
 
  scope :three_weeks_ago, lambda {where("line_items.last_eaten >= ? AND line_items.last_eaten <= ?", 22.days.ago.to_date, 15.days.ago.to_date)}
  
 
  
  def self.two_weeks_ago
    where("line_items.last_eaten >= ? AND line_items.last_eaten <= ?", 14.days.ago.to_date, 7.days.ago.to_date)
  end

  def self.this_week
    LineItem.order("RANDOM()").limit(3).to_a
  end
  

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  #before_action :set_recipe_collection, only: [:create]
  #before_action :set_recipe, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy, :last_eaten] 


  def index
   
    @line_items = LineItem.where(nil) 
    @line_items = LineItem.all

    @line_items = @line_items.created_by(current_user.id)

      respond_to do |format|
      format.html
      format.pdf do
        render pdf: "line_items", disposition: "inline", template: "line_items/index.html.erb"   # Excluding ".pdf" extension.
      end
      end


  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    recipe = Recipe.find(params[:recipe_id])
    user = current_user
    
    @line_item = user.line_items.build(recipe: recipe) 
    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.recipe, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def replace_weekly_line_item
    id_of_line_item_to_replace = params[:line_item_id].to_i
    current_ids_of_line_items_this_week = ids_of_line_items_this_week
    replacing_id = LineItem.where.not(id: current_ids_of_line_items_this_week)
                           .order("RANDOM()")
                           .first.id
    cookies[:this_week_line_item_ids] = current_ids_of_line_items_this_week - [id_of_line_item_to_replace] + [replacing_id]

    redirect_to action: :index
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.

    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:recipe_id, :recipe_collection_id, :last_eaten, :id_of_recipe_to_remove, :ingredient)
    end

    helper_method :ids_of_line_items_this_week
    def ids_of_line_items_this_week
      # line items of the week are stored in the cookie cookies[:this_week_line_item_ids]

      # first make it a blank string if it is nil
      cookies[:this_week_line_item_ids] = "" if cookies[:this_week_line_item_ids].nil?

      # Rails stores array of values in cookies in a string, where the values are joined with "&"
      # i.e. the array [1,2,3] is stored in the string "1&2&3"
      # to have the ids we need to "unjoin" (i.e. split) the string
      this_week_line_item_ids = cookies[:this_week_line_item_ids].split "&"
      # make sure the ids are integers, not strings
      #this_week_line_item_ids.map! { |id| id.to_i }

      # if we have less than 3 we complete by random other ones
      missing_line_items_nb = 7 - this_week_line_item_ids.size
      completing_line_item_ids = LineItem.order("RANDOM()")
                                         .where.not(id: this_week_line_item_ids)
                                         .limit(missing_line_items_nb)
                                         .pluck(:id)

      # we update the cookie so that now it also includes the completing ids
      cookies[:this_week_line_item_ids] = this_week_line_item_ids + completing_line_item_ids

      # we return the ids
      this_week_line_item_ids
    end
  
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/__menu.html.erb
<table>
	<th>Last week</th>
	<tr><%= @line_item.last_eaten %></tr>
	<td><%= @line_item.recipe.title %></td>
</table>

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">
    <%# f.label :recipe_id %><br>
    <%# f.text_field :recipe_id %>
  </div> -->
  <!--<div class="field">
    <%# f.label :recipe_collection_id %><br>
    <%# f.text_field :recipe_collection_id %>
  </div> -->
  <div class="field">
    <%= f.label :last_eaten %><br>
    <%= date_select(:line_item, :last_eaten, :use_two_digit_numbers => true) %>
  </div>
  <div class="actions">
    <%# button_to 'Add to Line Items', line_items_path(recipe_id :recipe) %>
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>


<p id="notice"><%= notice %></p>

<h1>Line Items</h1>
<p>Hi, <%= current_user.email %>! </p>

<div class="row">

 <div class="col-xs-6 col-sm-4" >
   
    <button class="btn btn-primary " type="button" data-toggle="collapse" data-target="#menu" aria-expanded="true" aria-controls="menu">
     This Week's Menu
    </button>
    <div class="collapse in" id="menu">
      <div class="well"> 
    <br>
      <% LineItem.where(id: ids_of_line_items_this_week).each do |line_item| %>
        <%# receta = line_item.recipe %>
        <li><%= line_item.recipe.title %> <%= link_to 'Replace', line_item_replace_weekly_line_item_path(line_item_id: line_item.id), method: :put, :class => "btn btn-default btn-xs" %>
        </li>
        <%end%>
        <br>
        <br>
        <p>Ingredients to buy:</p>
        <% LineItem.where(id: ids_of_line_items_this_week).each do |line_item| %>
        <% receta = line_item.recipe %>
          <% receta.ingredients.each do |ingredient| %>
          <li> <%= ingredient.name %> </li>
          <%end%>
          <%end%>
      </div>
    </div>
  </div> 
 
  <div class="col-xs-6 col-sm-4">
    <button class="btn btn-primary " type="button" data-toggle="collapse" data-target="#lastWeek" aria-expanded="false" aria-controls="lastWeek">
     Last Week's Menu
    </button>
      <div class="collapse" id="lastWeek">
        <div class="well">
          <p>Recipes Prepared <strong>Last</strong> Week</p>
            <% @line_items.last_week.each do |line_item| %>
              <li><%= line_item.recipe.title %></li>  <br>
            <% end %>
        </div>
      </div>
  </div>

  <div class="col-xs-6 col-sm-4">

    <button class="btn btn-primary " type="button" data-toggle="collapse" data-target="#twoWeeksAgo" aria-expanded="false" aria-controls="twoWeeksAgo">
      Menu from 2 Weeks Ago
    </button>
      <div class="collapse" id="twoWeeksAgo">
        <div class="well">
          <p>Recipes Prepared <strong>2 Weeks Ago</strong></p>
          <br>  
        <% @line_items.two_weeks_ago.each do |line_item| %>
          <%= line_item.recipe.title %> <br>
        <% end %>
      </div>
    </div>
  </div>
<!--End of Container for Menus -->
</div>  

<br>

<%= link_to "Download/Print a PDF", line_items_path(@line_items, format: "pdf")  %>
<br>
<br>
<br>

<button class="btn btn-primary " type="button" data-toggle="collapse" data-target="#favoriteRecipes" aria-expanded="false" aria-controls="favoriteRecipes">
  Favorite Recipes
</button>
<div class="collapse" id="favoriteRecipes">
  <div class="well">
<table>
  <thead>
    <tr>
      <th>Recipe</th>
      <!--<th>Recipe Collection</th> -->
      <th colspan="3">Last Eaten</th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.recipe.title %></td>
        <td><%= line_item.last_eaten %></td>
        <td><%= link_to 'Update', edit_line_item_path(line_item), :class => "btn btn-default btn-xs" %></td>
        <td><%= link_to 'Delete', line_item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default btn-xs" %></td>
    <% end %>
      </tr>
  </tbody>
</table>
</div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
  </div> 

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/replace_recipe.html.erb
<p>	
 <% @lineitems.this_week.each do |recipe |%>
	<ul>
		<li>
			<%= recipe %>
		</li>
		<% end %>
	</ul>
	
</p>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipe:</strong>
  <%= @line_item.recipe.title %>
</p>

<p>
  <strong>Recipe collection:</strong>
  <%= @line_item.recipe.title %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>